export interface Persona {
  id: string;
  projectId: string;
  name: string;
  role: string;
  jobToBeDone?: string;
  constraints?: string;
  successMetrics?: string;
  decisionCriteria?: string;
  vocabulary: string[];
  sampleQueries: string[];
  funnelStage: "education" | "comparison" | "purchase";
  avatarUrl?: string;
  isAutoGenerated: boolean;
  createdAt: string;
}
