import React from "react";
import { View, Text, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  footer: {
    position: "absolute",
    bottom: 24,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTop: "0.5 solid #e5e7eb",
    paddingTop: 6,
  },
  text: { fontSize: 7, color: "#9ca3af" },
});

export function ReportFooter({
  brandName,
}: {
  pageNumber?: number;
  brandName?: string;
}) {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.text}>{brandName ?? "Generated by LLM Rank"}</Text>
      <Text style={styles.text} render={({ pageNumber: pn }) => `Page ${pn}`} />
    </View>
  );
}
