import { eq, desc, sql } from "drizzle-orm";
import type { AppDatabase as Database } from "../d1-client";
import { personas } from "../schema";

function parseStringArray(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.filter((item): item is string => typeof item === "string");
  }
  if (typeof value !== "string" || value.trim().length === 0) return [];

  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed)
      ? parsed.filter((item): item is string => typeof item === "string")
      : [];
  } catch {
    return [];
  }
}

function deserializePersona<
  T extends { vocabulary: unknown; sampleQueries: unknown },
>(persona: T) {
  return {
    ...persona,
    vocabulary: parseStringArray(persona.vocabulary),
    sampleQueries: parseStringArray(persona.sampleQueries),
  };
}

export function personaQueries(db: Database) {
  return {
    async getById(id: string) {
      const persona = await db.query.personas.findFirst({
        where: eq(personas.id, id),
      });
      return persona ? deserializePersona(persona) : persona;
    },

    async listByProject(projectId: string) {
      const rows = await db.query.personas.findMany({
        where: eq(personas.projectId, projectId),
        orderBy: [desc(personas.createdAt)],
      });
      return rows.map(deserializePersona);
    },

    async countByProject(projectId: string) {
      const [row] = await db
        .select({ count: sql<number>`count(*)` })
        .from(personas)
        .where(eq(personas.projectId, projectId));
      return row?.count ?? 0;
    },

    async create(data: {
      projectId: string;
      name: string;
      role: string;
      jobToBeDone?: string;
      constraints?: string;
      successMetrics?: string;
      decisionCriteria?: string;
      vocabulary?: string[];
      sampleQueries?: string[];
      funnelStage?: "education" | "comparison" | "purchase";
      avatarUrl?: string;
      isAutoGenerated?: boolean;
    }) {
      const [persona] = await db
        .insert(personas)
        .values({
          ...data,
          id: crypto.randomUUID(),
          vocabulary: data.vocabulary
            ? JSON.stringify(data.vocabulary)
            : undefined,
          sampleQueries: data.sampleQueries
            ? JSON.stringify(data.sampleQueries)
            : undefined,
        })
        .returning();
      return persona ? deserializePersona(persona) : persona;
    },

    async update(
      id: string,
      data: Partial<{
        name: string;
        role: string;
        jobToBeDone: string;
        constraints: string;
        successMetrics: string;
        decisionCriteria: string;
        vocabulary: string[];
        sampleQueries: string[];
        funnelStage: "education" | "comparison" | "purchase";
        avatarUrl: string;
      }>,
    ) {
      const setData: Record<string, unknown> = { ...data };
      if (data.vocabulary !== undefined)
        setData.vocabulary = JSON.stringify(data.vocabulary);
      if (data.sampleQueries !== undefined)
        setData.sampleQueries = JSON.stringify(data.sampleQueries);
      const [updated] = await db
        .update(personas)
        .set(setData)
        .where(eq(personas.id, id))
        .returning();
      return updated ? deserializePersona(updated) : updated;
    },

    async remove(id: string) {
      const [deleted] = await db
        .delete(personas)
        .where(eq(personas.id, id))
        .returning();
      return deleted ? deserializePersona(deleted) : deleted;
    },
  };
}
