import { eq, desc, sql } from "drizzle-orm";
import type { Database } from "../client";
import { personas } from "../schema";

export function personaQueries(db: Database) {
  return {
    async getById(id: string) {
      return db.query.personas.findFirst({
        where: eq(personas.id, id),
      });
    },

    async listByProject(projectId: string) {
      return db.query.personas.findMany({
        where: eq(personas.projectId, projectId),
        orderBy: [desc(personas.createdAt)],
      });
    },

    async countByProject(projectId: string) {
      const [row] = await db
        .select({ count: sql<number>`count(*)::int` })
        .from(personas)
        .where(eq(personas.projectId, projectId));
      return row?.count ?? 0;
    },

    async create(data: {
      projectId: string;
      name: string;
      role: string;
      jobToBeDone?: string;
      constraints?: string;
      successMetrics?: string;
      decisionCriteria?: string;
      vocabulary?: string[];
      sampleQueries?: string[];
      funnelStage?: "education" | "comparison" | "purchase";
      avatarUrl?: string;
      isAutoGenerated?: boolean;
    }) {
      const [persona] = await db.insert(personas).values(data).returning();
      return persona;
    },

    async update(
      id: string,
      data: Partial<{
        name: string;
        role: string;
        jobToBeDone: string;
        constraints: string;
        successMetrics: string;
        decisionCriteria: string;
        vocabulary: string[];
        sampleQueries: string[];
        funnelStage: "education" | "comparison" | "purchase";
        avatarUrl: string;
      }>,
    ) {
      const [updated] = await db
        .update(personas)
        .set(data)
        .where(eq(personas.id, id))
        .returning();
      return updated;
    },

    async remove(id: string) {
      const [deleted] = await db
        .delete(personas)
        .where(eq(personas.id, id))
        .returning();
      return deleted;
    },
  };
}
