import {
  Document,
  FileChild,
  Paragraph,
  TextRun,
  AlignmentType,
  HeadingLevel,
  Header,
  Footer,
  PageNumber,
} from "docx";
import type { ReportData } from "../../types";
import {
  heading,
  bodyText,
  spacer,
  scoreText,
  simpleTable,
  bulletList,
} from "../builders";
import { gradeColor, BRAND_COLOR, GRAY_400, GRAY_600 } from "../styles";

export function buildSummaryDocx(data: ReportData): Document {
  const brandName = data.project.branding?.companyName ?? "LLM Boost";
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const sections = [];

  // --- Cover section ---
  const coverParagraphs = [
    spacer(),
    spacer(),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "AI-Readiness Report",
          size: 56,
          bold: true,
          color: "1F2937",
        }),
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: data.project.domain,
          size: 28,
          color: BRAND_COLOR,
        }),
      ],
      spacing: { after: 200 },
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: `Overall Score: ${Math.round(data.scores.overall)} (${data.scores.letterGrade})`,
          size: 36,
          bold: true,
          color: gradeColor(data.scores.overall),
        }),
      ],
      spacing: { after: 200 },
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: `${data.crawl.pagesScored} pages analyzed | ${date}`,
          size: 20,
          color: GRAY_600,
        }),
      ],
    }),
  ];

  if (data.config.preparedFor) {
    coverParagraphs.push(
      spacer(),
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: `Prepared for ${data.config.preparedFor}`,
            size: 22,
            color: GRAY_600,
          }),
        ],
      }),
    );
  }

  sections.push({ children: coverParagraphs });

  // --- Scores + Summary section ---
  const scoresParagraphs: FileChild[] = [
    heading("Category Scorecard", HeadingLevel.HEADING_1),
    scoreText(
      "Technical SEO",
      data.scores.technical,
      gradeColor(data.scores.technical),
    ),
    scoreText(
      "Content Quality",
      data.scores.content,
      gradeColor(data.scores.content),
    ),
    scoreText(
      "AI Readiness",
      data.scores.aiReadiness,
      gradeColor(data.scores.aiReadiness),
    ),
    scoreText(
      "Performance",
      data.scores.performance,
      gradeColor(data.scores.performance),
    ),
    spacer(),
  ];

  if (data.crawl.summary) {
    scoresParagraphs.push(
      heading("Executive Summary", HeadingLevel.HEADING_1),
      bodyText(data.crawl.summary),
      spacer(),
    );
  }

  // Quick wins
  scoresParagraphs.push(heading("Top Quick Wins", HeadingLevel.HEADING_1));
  const wins = data.quickWins.slice(0, 5);
  scoresParagraphs.push(
    ...bulletList(
      wins.map((w, i) => ({
        text: `${i + 1}. ${w.message}`,
        detail: `${w.recommendation} | +${w.scoreImpact} pts | ${w.affectedPages} pages | Effort: ${w.effort}${w.roi.trafficEstimate ? ` | ${w.roi.trafficEstimate}` : ""}`,
      })),
    ),
  );

  // Visibility snapshot
  if (data.visibility) {
    scoresParagraphs.push(
      spacer(),
      heading("AI Visibility Snapshot", HeadingLevel.HEADING_1),
      simpleTable(
        ["Platform", "Brand Mentions", "URL Citations", "Checks"],
        data.visibility.platforms.map((p) => [
          p.provider.charAt(0).toUpperCase() + p.provider.slice(1),
          `${p.brandMentionRate}%`,
          `${p.urlCitationRate}%`,
          String(p.checksCount),
        ]),
      ),
    );
  }

  sections.push({
    headers: {
      default: new Header({
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: brandName,
                color: BRAND_COLOR,
                size: 16,
                bold: true,
              }),
              new TextRun({
                text: ` | ${data.project.domain}`,
                color: GRAY_400,
                size: 16,
              }),
            ],
          }),
        ],
      }),
    },
    footers: {
      default: new Footer({
        children: [
          new Paragraph({
            alignment: AlignmentType.RIGHT,
            children: [
              new TextRun({
                text: `Generated by ${brandName} | Page `,
                color: GRAY_400,
                size: 16,
              }),
              new TextRun({
                children: [PageNumber.CURRENT],
                color: GRAY_400,
                size: 16,
              }),
            ],
          }),
        ],
      }),
    },
    children: scoresParagraphs,
  });

  return new Document({
    title: `AI-Readiness Report - ${data.project.domain}`,
    description: `Generated by ${brandName}`,
    sections,
  });
}
