"use client";

import { useState, useCallback } from "react";
import { api, ApiError } from "@/lib/api";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface PersonaInput {
  label: string;
  role: string;
  custom: boolean;
  jobToBeDone?: string;
}

interface DiscoverySaveInput {
  projectId: string;
  businessGoal: string | null;
  personas: PersonaInput[];
  keywords: string[];
  competitors: string[];
}

interface DiscoverySaveResult {
  saving: boolean;
  error: string | null;
  save: (input: DiscoverySaveInput) => Promise<boolean>;
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export function useDiscoverySave(): DiscoverySaveResult {
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const save = useCallback(
    async (input: DiscoverySaveInput): Promise<boolean> => {
      setSaving(true);
      setError(null);

      try {
        const promises: Promise<unknown>[] = [];

        // 1. Save business goal on the project
        if (input.businessGoal) {
          promises.push(
            api.projects.update(input.projectId, {
              businessGoal: input.businessGoal as
                | "ai_mentions"
                | "lead_gen"
                | "outrank"
                | "brand_understanding",
            }),
          );
        }

        // 2. Create each persona
        for (const p of input.personas) {
          promises.push(
            api.personas.create(input.projectId, {
              name: p.label,
              role: p.role,
              funnelStage: "education",
              isAutoGenerated: !p.custom,
              jobToBeDone: p.jobToBeDone || `${p.role} — evaluating solutions`,
            }),
          );
        }

        // 3. Batch-create keywords
        if (input.keywords.length > 0) {
          promises.push(
            api.keywords.createBatch(input.projectId, input.keywords),
          );
        }

        // 4. Save competitors via strategy API.
        //    This route is Pro-gated — for free users the competitors card is
        //    auto-skipped so there will be nothing to save. If a plan mismatch
        //    somehow occurs, Promise.allSettled lets it fail silently.
        for (const domain of input.competitors) {
          promises.push(api.strategy.addCompetitor(input.projectId, domain));
        }

        const results = await Promise.allSettled(promises);

        // Check if any non-competitor promise rejected (competitor failures are
        // expected for free-tier and can be silently swallowed).
        const nonCompetitorCount =
          (input.businessGoal ? 1 : 0) +
          input.personas.length +
          (input.keywords.length > 0 ? 1 : 0);

        const criticalResults = results.slice(0, nonCompetitorCount);
        const failures = criticalResults.filter((r) => r.status === "rejected");

        if (failures.length > 0) {
          const firstReason = (failures[0] as PromiseRejectedResult).reason;
          const message =
            firstReason instanceof ApiError
              ? firstReason.message
              : "Some selections could not be saved. You can update them from the dashboard.";
          setError(message);
          return false;
        }

        return true;
      } catch (err) {
        const message =
          err instanceof ApiError
            ? err.message
            : "Failed to save discovery selections. Please try again.";
        setError(message);
        return false;
      } finally {
        setSaving(false);
      }
    },
    [],
  );

  return { saving, error, save };
}
