import { beforeEach, describe, expect, it, vi } from "vitest";
import { createTestApp } from "../helpers/test-app";

vi.mock("../../middleware/auth", () => ({
  authMiddleware: vi.fn().mockImplementation(async (_c: any, next: any) => {
    await next();
  }),
}));

const mockMessagesCreate = vi.fn();

vi.mock("@anthropic-ai/sdk", () => ({
  default: vi.fn().mockImplementation(() => ({
    messages: { create: mockMessagesCreate },
  })),
}));

const mockProjectGetById = vi.fn();
const mockUserGetById = vi.fn();
const mockPersonas = {
  listByProject: vi.fn(),
  countByProject: vi.fn(),
  create: vi.fn(),
  getById: vi.fn(),
  update: vi.fn(),
  remove: vi.fn(),
};

vi.mock("@llm-boost/db", async (importOriginal) => {
  const orig = await importOriginal<typeof import("@llm-boost/db")>();
  return {
    ...orig,
    projectQueries: () => ({
      getById: mockProjectGetById,
    }),
    userQueries: () => ({
      getById: mockUserGetById,
    }),
    personaQueries: () => mockPersonas,
    createAppDb: orig.createAppDb,
  };
});

vi.mock("@llm-boost/repositories", () => ({
  createProjectRepository: () => ({}),
  createUserRepository: () => ({}),
  createCrawlRepository: () => ({}),
  createScoreRepository: () => ({}),
  createPageRepository: () => ({}),
}));

describe("Persona Routes", () => {
  const { request } = createTestApp();
  const projectId = "cd19e84d-0b41-4e09-b908-c36bb39ca399";

  beforeEach(() => {
    vi.clearAllMocks();
    mockUserGetById.mockResolvedValue({
      id: "test-user-id",
      plan: "agency",
    });
    mockProjectGetById.mockResolvedValue({
      id: projectId,
      userId: "test-user-id",
      name: "families.care",
      domain: "families.care",
    });
  });

  it("returns a fallback persona draft when the LLM provider is usage-limited", async () => {
    mockMessagesCreate.mockRejectedValue(
      new Error(
        '400 {"type":"error","error":{"type":"invalid_request_error","message":"You have reached your specified API usage limits."}}',
      ),
    );

    const res = await request(`/api/personas/${projectId}/generate`, {
      method: "POST",
      json: {
        role: "Adult daughter researching assisted living for a parent",
      },
    });

    expect(res.status).toBe(200);
    const body: any = await res.json();
    expect(body.meta).toEqual({
      source: "fallback",
      reason: "llm_provider_unavailable",
    });
    expect(body.data).toMatchObject({
      name: "Adult daughter researching assisted living for a parent",
      role: "Adult daughter researching assisted living for a parent",
      funnelStage: "comparison",
      isAutoGenerated: true,
    });
    expect(body.data.sampleQueries).toEqual(
      expect.arrayContaining([expect.stringContaining("families.care")]),
    );
  });
});
