import { Hono } from "hono";
import type { AppEnv } from "../index";
import { authMiddleware } from "../middleware/auth";
import { personaQueries, userQueries, projectQueries } from "@llm-boost/db";
import { PLAN_LIMITS } from "@llm-boost/shared";
import { handleServiceError } from "../lib/error-handler";
import { trackLlmUsage } from "../lib/llm-usage-tracker";

export const personaRoutes = new Hono<AppEnv>();
personaRoutes.use("*", authMiddleware);

type GeneratedPersonaDraft = {
  name: string;
  role: string;
  jobToBeDone: string;
  constraints: string;
  successMetrics: string;
  decisionCriteria: string;
  vocabulary: string[];
  sampleQueries: string[];
  funnelStage: "education" | "comparison" | "purchase";
  isAutoGenerated: boolean;
};

function projectDisplayName(project: { name?: string | null; domain: string }) {
  return project.name?.trim() || project.domain.replace(/^www\./, "");
}

function buildFallbackPersona(
  project: { name?: string | null; domain: string },
  roleName: string,
): GeneratedPersonaDraft {
  const role = roleName.trim();
  const businessName = projectDisplayName(project);
  const domain = project.domain
    .replace(/^https?:\/\//, "")
    .replace(/^www\./, "");

  return {
    name: role,
    role,
    jobToBeDone: `Evaluate ${businessName} and compare trustworthy options so they can make a confident decision.`,
    constraints:
      "Limited research time, unclear vendor claims, budget sensitivity, and a need for clear proof before taking action.",
    successMetrics:
      "Can identify the best-fit option, understand costs and tradeoffs, and move from research to a short list of next steps.",
    decisionCriteria:
      "Trust signals, transparent pricing, relevant proof, ease of comparison, implementation effort, and quality of support.",
    vocabulary: [
      businessName,
      domain,
      role,
      "reviews",
      "pricing",
      "alternatives",
      "comparison",
    ],
    sampleQueries: [
      `is ${businessName} right for ${role.toLowerCase()}`,
      `${businessName} reviews and pricing`,
      `best ${businessName} alternatives`,
      `how to compare options for ${role.toLowerCase()}`,
    ],
    funnelStage: "comparison",
    isAutoGenerated: true,
  };
}

function isRecoverablePersonaGenerationError(error: unknown) {
  const message =
    error instanceof Error ? error.message : JSON.stringify(error ?? "");
  return /usage limits|rate[_ -]?limit|quota|overloaded|temporarily unavailable/i.test(
    message,
  );
}

// List personas for a project
personaRoutes.get("/:projectId", async (c) => {
  const db = c.get("db");
  const userId = c.get("userId");
  const projectId = c.req.param("projectId");

  const project = await projectQueries(db).getById(projectId);
  if (!project || project.userId !== userId) {
    return c.json(
      { error: { code: "NOT_FOUND", message: "Project not found" } },
      404,
    );
  }

  const personas = await personaQueries(db).listByProject(projectId);
  return c.json({ data: personas });
});

// Create persona (manual or AI-generated)
personaRoutes.post("/:projectId", async (c) => {
  const db = c.get("db");
  const userId = c.get("userId");
  const projectId = c.req.param("projectId");

  try {
    const project = await projectQueries(db).getById(projectId);
    if (!project || project.userId !== userId) {
      return c.json(
        { error: { code: "NOT_FOUND", message: "Project not found" } },
        404,
      );
    }

    const user = await userQueries(db).getById(userId);
    const limits =
      PLAN_LIMITS[
        (user?.plan ?? "free") as import("@llm-boost/shared").PlanTier
      ];
    const count = await personaQueries(db).countByProject(projectId);

    if (count >= limits.personasPerProject) {
      return c.json(
        {
          error: {
            code: "PLAN_LIMIT_REACHED",
            message: `Your plan allows ${limits.personasPerProject} personas per project.`,
          },
        },
        403,
      );
    }

    const body = await c.req.json();
    const persona = await personaQueries(db).create({
      projectId,
      name: body.name,
      role: body.role ?? body.name,
      jobToBeDone: body.jobToBeDone,
      constraints: body.constraints,
      successMetrics: body.successMetrics,
      decisionCriteria: body.decisionCriteria,
      vocabulary: body.vocabulary ?? [],
      sampleQueries: body.sampleQueries ?? [],
      funnelStage: body.funnelStage ?? "education",
      avatarUrl: body.avatarUrl,
      isAutoGenerated: body.isAutoGenerated ?? false,
    });

    return c.json({ data: persona }, 201);
  } catch (error) {
    return handleServiceError(c, error);
  }
});

// Update persona
personaRoutes.patch("/:id", async (c) => {
  const db = c.get("db");
  const userId = c.get("userId");
  const id = c.req.param("id");

  try {
    const persona = await personaQueries(db).getById(id);
    if (!persona) {
      return c.json(
        { error: { code: "NOT_FOUND", message: "Persona not found" } },
        404,
      );
    }

    const project = await projectQueries(db).getById(persona.projectId);
    if (!project || project.userId !== userId) {
      return c.json(
        { error: { code: "NOT_FOUND", message: "Persona not found" } },
        404,
      );
    }

    const body = await c.req.json();
    const updated = await personaQueries(db).update(id, body);
    return c.json({ data: updated });
  } catch (error) {
    return handleServiceError(c, error);
  }
});

// Delete persona
personaRoutes.delete("/:id", async (c) => {
  const db = c.get("db");
  const userId = c.get("userId");
  const id = c.req.param("id");

  try {
    const persona = await personaQueries(db).getById(id);
    if (!persona) {
      return c.json(
        { error: { code: "NOT_FOUND", message: "Persona not found" } },
        404,
      );
    }

    const project = await projectQueries(db).getById(persona.projectId);
    if (!project || project.userId !== userId) {
      return c.json(
        { error: { code: "NOT_FOUND", message: "Persona not found" } },
        404,
      );
    }

    await personaQueries(db).remove(id);
    return c.body(null, 204);
  } catch (error) {
    return handleServiceError(c, error);
  }
});

// AI-generate a persona from a role name
personaRoutes.post("/:projectId/generate", async (c) => {
  const db = c.get("db");
  const userId = c.get("userId");
  const projectId = c.req.param("projectId");

  try {
    const user = await userQueries(db).getById(userId);
    const limits =
      PLAN_LIMITS[
        (user?.plan ?? "free") as import("@llm-boost/shared").PlanTier
      ];
    if (!limits.personaRefinement) {
      return c.json(
        {
          error: {
            code: "PLAN_LIMIT_REACHED",
            message: "AI persona generation requires Starter plan or higher.",
          },
        },
        403,
      );
    }

    const project = await projectQueries(db).getById(projectId);
    if (!project || project.userId !== userId) {
      return c.json(
        { error: { code: "NOT_FOUND", message: "Project not found" } },
        404,
      );
    }

    const body = await c.req.json();
    const roleName = body.role;
    if (!roleName) {
      return c.json(
        {
          error: {
            code: "VALIDATION_ERROR",
            message: "role is required",
          },
        },
        422,
      );
    }

    if (!c.env.ANTHROPIC_API_KEY) {
      return c.json({
        data: buildFallbackPersona(project, roleName),
        meta: { source: "fallback", reason: "missing_anthropic_api_key" },
      });
    }

    const prompt = `Generate a detailed audience persona for someone with the role "${roleName}" who would be searching for a product/service like this:
Domain: ${project.domain}
Name: ${project.name}

Return ONLY valid JSON with: { "name", "role", "jobToBeDone", "constraints", "successMetrics", "decisionCriteria", "vocabulary": [], "sampleQueries": [], "funnelStage": "education"|"comparison"|"purchase" }`;

    try {
      const { default: Anthropic } = await import("@anthropic-ai/sdk");
      const anthropic = new Anthropic({ apiKey: c.env.ANTHROPIC_API_KEY });
      const response = await anthropic.messages.create({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 1024,
        messages: [{ role: "user", content: prompt }],
      });

      await trackLlmUsage(c.get("db"), {
        feature: "personas",
        model: "claude-haiku-4-5-20251001",
        inputTokens: response.usage.input_tokens,
        outputTokens: response.usage.output_tokens,
        userId: c.get("userId"),
        projectId: project.id,
      });

      const text =
        response.content[0]?.type === "text" ? response.content[0].text : "{}";
      const cleaned = text.replace(/```json\n?|\n?```/g, "").trim();
      const generated = JSON.parse(cleaned);

      return c.json({ data: generated });
    } catch (error) {
      if (!isRecoverablePersonaGenerationError(error)) throw error;

      return c.json({
        data: buildFallbackPersona(project, roleName),
        meta: { source: "fallback", reason: "llm_provider_unavailable" },
      });
    }
  } catch (error) {
    return handleServiceError(c, error);
  }
});

// AI-refine a persona (suggest improvements)
personaRoutes.post("/:id/refine", async (c) => {
  const db = c.get("db");
  const userId = c.get("userId");
  const id = c.req.param("id");

  try {
    const user = await userQueries(db).getById(userId);
    const limits =
      PLAN_LIMITS[
        (user?.plan ?? "free") as import("@llm-boost/shared").PlanTier
      ];
    if (!limits.personaRefinement) {
      return c.json(
        {
          error: {
            code: "PLAN_LIMIT_REACHED",
            message: "AI persona refinement requires Starter plan or higher.",
          },
        },
        403,
      );
    }

    const persona = await personaQueries(db).getById(id);
    if (!persona) {
      return c.json(
        { error: { code: "NOT_FOUND", message: "Persona not found" } },
        404,
      );
    }

    const project = await projectQueries(db).getById(persona.projectId);
    if (!project || project.userId !== userId) {
      return c.json(
        { error: { code: "NOT_FOUND", message: "Persona not found" } },
        404,
      );
    }

    const { default: Anthropic } = await import("@anthropic-ai/sdk");
    const anthropic = new Anthropic({ apiKey: c.env.ANTHROPIC_API_KEY });

    const prompt = `Review this audience persona and suggest specific improvements to make it more useful for AI search tracking:

Current persona:
${JSON.stringify(persona, null, 2)}

For the website: ${project.domain} (${project.name})

Suggest improvements for each field. Focus on:
- More specific job-to-be-done descriptions
- More realistic vocabulary and phrasing patterns
- Better sample queries that someone in this role would actually type into ChatGPT/Perplexity
- Missing constraints or decision criteria

Return ONLY valid JSON with the same structure as the input, with improved values.`;

    const response = await anthropic.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 1024,
      messages: [{ role: "user", content: prompt }],
    });

    await trackLlmUsage(c.get("db"), {
      feature: "personas_refine",
      model: "claude-haiku-4-5-20251001",
      inputTokens: response.usage.input_tokens,
      outputTokens: response.usage.output_tokens,
      userId: c.get("userId"),
      projectId: persona.projectId,
    });

    const text =
      response.content[0]?.type === "text" ? response.content[0].text : "{}";
    const cleaned = text.replace(/```json\n?|\n?```/g, "").trim();
    const suggestions = JSON.parse(cleaned);

    return c.json({ data: suggestions });
  } catch (error) {
    return handleServiceError(c, error);
  }
});
