import {
  createDb,
  personaQueries,
  projectQueries,
  userQueries,
} from "@llm-boost/db";
import { PLAN_LIMITS } from "@llm-boost/shared";
import { createLogger } from "@llm-boost/shared";

export interface AutoPersonaInput {
  databaseUrl: string;
  projectId: string;
  anthropicApiKey: string;
}

export async function runAutoPersonaGeneration(
  input: AutoPersonaInput,
): Promise<void> {
  const log = createLogger({ context: "auto-persona" });
  const db = createDb(input.databaseUrl);

  const project = await projectQueries(db).getById(input.projectId);
  if (!project) return;

  const user = await userQueries(db).getById(project.userId);
  if (!user) return;

  const limits = PLAN_LIMITS[user.plan];
  if (!limits.personaRefinement) {
    log.info("Auto-persona skipped: free plan", {
      projectId: input.projectId,
    });
    return;
  }

  const existing = await personaQueries(db).countByProject(input.projectId);
  if (existing > 0) {
    log.info("Auto-persona skipped: personas already exist", {
      projectId: input.projectId,
    });
    return;
  }

  const { default: Anthropic } = await import("@anthropic-ai/sdk");
  const anthropic = new Anthropic({ apiKey: input.anthropicApiKey });

  const prompt = `Generate 3 audience personas for a website. Each persona represents someone who would search for this product/service using AI search engines like ChatGPT or Perplexity.

Domain: ${project.domain}
Name: ${project.name}

Return ONLY valid JSON array with 3 objects, each having: { "name", "role", "jobToBeDone", "constraints", "successMetrics", "decisionCriteria", "vocabulary": [], "sampleQueries": [], "funnelStage": "education"|"comparison"|"purchase" }`;

  try {
    const response = await anthropic.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 2048,
      messages: [{ role: "user", content: prompt }],
    });

    const text =
      response.content[0]?.type === "text" ? response.content[0].text : "[]";
    const cleaned = text.replace(/```json\n?|\n?```/g, "").trim();
    const personas = JSON.parse(cleaned);

    if (!Array.isArray(personas)) return;

    const maxToCreate = Math.min(
      personas.length,
      limits.personasPerProject - existing,
    );

    for (const p of personas.slice(0, maxToCreate)) {
      await personaQueries(db).create({
        projectId: input.projectId,
        name: p.name ?? "Auto-generated Persona",
        role: p.role ?? p.name,
        jobToBeDone: p.jobToBeDone,
        constraints: p.constraints,
        successMetrics: p.successMetrics,
        decisionCriteria: p.decisionCriteria,
        vocabulary: p.vocabulary ?? [],
        sampleQueries: p.sampleQueries ?? [],
        funnelStage: p.funnelStage ?? "education",
        isAutoGenerated: true,
      });
    }

    log.info(`Auto-persona created ${maxToCreate} personas`, {
      projectId: input.projectId,
    });
  } catch (err) {
    log.error("Auto-persona generation failed", { error: String(err) });
  }
}
