import { act, renderHook } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { api, type StrategyPersona } from "@/lib/api";
import { useStrategyTabActions } from "./use-strategy-tab-actions";

const { toastMock } = vi.hoisted(() => ({
  toastMock: vi.fn(),
}));

vi.mock("@/components/ui/use-toast", () => ({
  useToast: () => ({ toast: toastMock }),
}));

describe("useStrategyTabActions", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    api.personas.create = vi.fn(async () => undefined);
    api.visibility.suggestKeywords = vi.fn(async () => ["alpha", "beta"]);
    api.keywords.createBatch = vi.fn(async () => undefined);
    api.visibility.schedules.create = vi.fn(async () => undefined);
    api.benchmarks.trigger = vi.fn(async () => undefined);
  });

  it("persists only new generated personas and refreshes the workspace", async () => {
    const existingPersonas: StrategyPersona[] = [
      {
        name: "Ops Leader",
        role: "Director",
        demographics: "B2B SaaS",
        goals: ["Improve AI visibility"],
        pains: ["Limited resources"],
        keywords: ["ai seo"],
        typicalQueries: ["best ai seo tools"],
      },
    ];
    const generatedPersonas: StrategyPersona[] = [
      existingPersonas[0],
      {
        name: "Content Manager",
        role: "Manager",
        demographics: "Mid-market",
        goals: ["Increase discovery"],
        pains: ["Low bandwidth"],
        keywords: ["content optimization"],
        typicalQueries: ["how to improve ai search presence"],
      },
    ];
    const generatePersonas = vi.fn(async () => generatedPersonas);
    const mutatePersistedPersonas = vi.fn(async () => undefined);

    const { result } = renderHook(() =>
      useStrategyTabActions({
        projectId: "proj-1",
        personaError: null,
        persistedPersonas: existingPersonas,
        savedKeywords: [],
        visibilitySchedules: [],
        recommendedCompetitorDomains: [],
        generatePersonas,
        addCompetitor: vi.fn(async () => undefined),
        removeCompetitor: vi.fn(async () => undefined),
        mutatePersistedPersonas,
        mutateSavedKeywords: vi.fn(async () => undefined),
        mutateVisibilitySchedules: vi.fn(async () => undefined),
      }),
    );

    await act(async () => {
      await result.current.handleGeneratePersonas();
    });

    expect(generatePersonas).toHaveBeenCalledWith(
      "AI SEO and Content Optimization",
    );
    expect(api.personas.create).toHaveBeenCalledTimes(1);
    expect(api.personas.create).toHaveBeenCalledWith("proj-1", {
      name: "Content Manager",
      role: "Manager",
      jobToBeDone: "Increase discovery",
      constraints: "Low bandwidth",
      vocabulary: ["content optimization"],
      sampleQueries: ["how to improve ai search presence"],
      isAutoGenerated: true,
      funnelStage: "education",
    });
    expect(mutatePersistedPersonas).toHaveBeenCalledTimes(1);
    expect(toastMock).toHaveBeenCalledWith({
      title: "Personas saved",
      description: "1 personas added to your persistent workspace.",
    });
  });

  it("discovers keywords, tracks selection changes, and accepts them into tracking", async () => {
    const mutateSavedKeywords = vi.fn(async () => undefined);
    const mutateVisibilitySchedules = vi.fn(async () => undefined);

    const { result } = renderHook(() =>
      useStrategyTabActions({
        projectId: "proj-1",
        personaError: null,
        persistedPersonas: [],
        savedKeywords: [{ keyword: "alpha" }],
        visibilitySchedules: [],
        recommendedCompetitorDomains: [],
        generatePersonas: vi.fn(async () => []),
        addCompetitor: vi.fn(async () => undefined),
        removeCompetitor: vi.fn(async () => undefined),
        mutatePersistedPersonas: vi.fn(async () => undefined),
        mutateSavedKeywords,
        mutateVisibilitySchedules,
      }),
    );

    await act(async () => {
      await result.current.handleDiscoverKeywordSuggestions();
    });

    expect(api.visibility.suggestKeywords).toHaveBeenCalledWith("proj-1");
    expect(result.current.keywordSuggestions).toEqual(["beta"]);
    expect(result.current.selectedSuggestions).toEqual(["beta"]);

    act(() => {
      result.current.handleToggleSuggestion("beta");
      result.current.handleToggleSuggestion("gamma");
    });

    expect(result.current.selectedSuggestions).toEqual(["gamma"]);

    await act(async () => {
      await result.current.handleAcceptSuggestedKeywords(["gamma"]);
    });

    expect(api.keywords.createBatch).toHaveBeenCalledWith("proj-1", ["gamma"]);
    expect(mutateSavedKeywords).toHaveBeenCalledTimes(1);
    expect(api.visibility.schedules.create).toHaveBeenCalledWith({
      projectId: "proj-1",
      query: "gamma",
      providers: ["chatgpt", "claude", "perplexity", "gemini"],
      frequency: "weekly",
    });
    expect(mutateVisibilitySchedules).toHaveBeenCalledTimes(1);
  });

  it("runs the guided demand flow and queues recommended competitors", async () => {
    const generatedPersonas: StrategyPersona[] = [
      {
        name: "Ops Leader",
        role: "Director",
        demographics: "B2B SaaS",
        goals: ["Improve AI visibility"],
        pains: ["Limited resources"],
        keywords: ["ai seo"],
        typicalQueries: ["best ai seo tools"],
      },
    ];
    const generatePersonas = vi.fn(async () => generatedPersonas);

    const { result } = renderHook(() =>
      useStrategyTabActions({
        projectId: "proj-1",
        personaError: null,
        persistedPersonas: [],
        savedKeywords: [],
        visibilitySchedules: [],
        recommendedCompetitorDomains: ["comp-a.com", "comp-b.com"],
        generatePersonas,
        addCompetitor: vi.fn(async () => undefined),
        removeCompetitor: vi.fn(async () => undefined),
        mutatePersistedPersonas: vi.fn(async () => undefined),
        mutateSavedKeywords: vi.fn(async () => undefined),
        mutateVisibilitySchedules: vi.fn(async () => undefined),
      }),
    );

    await act(async () => {
      await result.current.handleRunDemandFlow();
    });

    expect(generatePersonas).toHaveBeenCalledWith(
      "AI SEO and Content Optimization",
    );
    expect(api.visibility.suggestKeywords).toHaveBeenCalledWith("proj-1");
    expect(api.keywords.createBatch).toHaveBeenCalledWith("proj-1", [
      "alpha",
      "beta",
    ]);
    expect(api.benchmarks.trigger).toHaveBeenCalledTimes(2);
    expect(api.benchmarks.trigger).toHaveBeenCalledWith({
      projectId: "proj-1",
      competitorDomain: "comp-a.com",
    });
    expect(api.benchmarks.trigger).toHaveBeenCalledWith({
      projectId: "proj-1",
      competitorDomain: "comp-b.com",
    });
    expect(toastMock).toHaveBeenCalledWith({
      title: "Guided demand flow completed",
      description:
        "Personas, keywords, competitors, and schedules were advanced.",
    });
  });

  it("adds and removes competitors through the injected strategy actions", async () => {
    const addCompetitor = vi.fn(async () => undefined);
    const removeCompetitor = vi.fn(async () => undefined);

    const { result } = renderHook(() =>
      useStrategyTabActions({
        projectId: "proj-1",
        personaError: null,
        persistedPersonas: [],
        savedKeywords: [],
        visibilitySchedules: [],
        recommendedCompetitorDomains: [],
        generatePersonas: vi.fn(async () => []),
        addCompetitor,
        removeCompetitor,
        mutatePersistedPersonas: vi.fn(async () => undefined),
        mutateSavedKeywords: vi.fn(async () => undefined),
        mutateVisibilitySchedules: vi.fn(async () => undefined),
      }),
    );

    act(() => {
      result.current.setNewCompDomain("example.com");
    });

    await act(async () => {
      await result.current.handleAddCompetitor();
      await result.current.handleRemoveCompetitor("comp-1");
    });

    expect(addCompetitor).toHaveBeenCalledWith("example.com");
    expect(removeCompetitor).toHaveBeenCalledWith("comp-1");
    expect(result.current.newCompDomain).toBe("");
  });
});
