import { useCallback, useState } from "react";
import { useToast } from "@/components/ui/use-toast";
import { api, type StrategyPersona } from "@/lib/api";
import {
  buildPersonaIdentityKey,
  DEFAULT_VISIBILITY_PROVIDERS,
  DEMAND_FLOW_NICHE,
  getSuggestedKeywordSelection,
  toggleSelectedKeyword,
} from "./strategy-tab-helpers";

type AsyncMutator = () => Promise<unknown>;

type UseStrategyTabActionsArgs = {
  projectId: string;
  personaError: string | null;
  persistedPersonas: Array<Pick<StrategyPersona, "name" | "role">> | undefined;
  savedKeywords: Array<{ keyword: string }> | undefined;
  visibilitySchedules: unknown[] | undefined;
  recommendedCompetitorDomains: string[];
  generatePersonas: (niche: string) => Promise<StrategyPersona[]>;
  addCompetitor: (domain: string) => Promise<unknown>;
  removeCompetitor: (id: string) => Promise<unknown>;
  mutatePersistedPersonas: AsyncMutator;
  mutateSavedKeywords: AsyncMutator;
  mutateVisibilitySchedules: AsyncMutator;
};

export function useStrategyTabActions({
  projectId,
  personaError,
  persistedPersonas,
  savedKeywords,
  visibilitySchedules,
  recommendedCompetitorDomains,
  generatePersonas,
  addCompetitor,
  removeCompetitor,
  mutatePersistedPersonas,
  mutateSavedKeywords,
  mutateVisibilitySchedules,
}: UseStrategyTabActionsArgs) {
  const { toast } = useToast();
  const [addingComp, setAddingComp] = useState(false);
  const [newCompDomain, setNewCompDomain] = useState("");
  const [keywordSuggestions, setKeywordSuggestions] = useState<string[]>([]);
  const [selectedSuggestions, setSelectedSuggestions] = useState<string[]>([]);
  const [discoveringKeywords, setDiscoveringKeywords] = useState(false);
  const [acceptingKeywords, setAcceptingKeywords] = useState(false);
  const [addingRecommendedCompetitors, setAddingRecommendedCompetitors] =
    useState(false);
  const [runningDemandFlow, setRunningDemandFlow] = useState(false);

  const persistGeneratedPersonas = useCallback(
    async (personaSet: StrategyPersona[]) => {
      const existingKeys = new Set(
        (persistedPersonas ?? []).map((persona) =>
          buildPersonaIdentityKey(persona),
        ),
      );

      let created = 0;
      for (const persona of personaSet) {
        const key = buildPersonaIdentityKey(persona);
        if (existingKeys.has(key)) continue;

        await api.personas.create(projectId, {
          name: persona.name,
          role: persona.role,
          jobToBeDone: persona.goals?.[0] ?? undefined,
          constraints: persona.pains?.slice(0, 2).join("; ") ?? undefined,
          vocabulary: persona.keywords ?? [],
          sampleQueries: persona.typicalQueries ?? [],
          isAutoGenerated: true,
          funnelStage: "education",
        });

        existingKeys.add(key);
        created += 1;
      }

      if (created > 0) {
        await mutatePersistedPersonas();
        toast({
          title: "Personas saved",
          description: `${created} personas added to your persistent workspace.`,
        });
      }
    },
    [mutatePersistedPersonas, persistedPersonas, projectId, toast],
  );

  const handleGeneratePersonas = useCallback(async () => {
    try {
      const generated = await generatePersonas(DEMAND_FLOW_NICHE);
      await persistGeneratedPersonas(generated);
    } catch {
      toast({
        title: "Error",
        description: personaError ?? "Failed to generate personas",
        variant: "destructive",
      });
    }
  }, [generatePersonas, personaError, persistGeneratedPersonas, toast]);

  const discoverKeywordSuggestions = useCallback(async (): Promise<
    string[]
  > => {
    const suggested = await api.visibility.suggestKeywords(projectId);
    const { filtered, autoSelected } = getSuggestedKeywordSelection({
      suggestedKeywords: suggested,
      savedKeywords,
    });

    setKeywordSuggestions(filtered);
    setSelectedSuggestions(autoSelected);

    if (filtered.length === 0) {
      toast({
        title: "No new keyword suggestions",
        description: "Your current keyword list already covers suggestions.",
      });
    }

    return autoSelected;
  }, [projectId, savedKeywords, toast]);

  const handleDiscoverKeywordSuggestions = useCallback(async () => {
    setDiscoveringKeywords(true);
    try {
      await discoverKeywordSuggestions();
    } catch (err) {
      toast({
        title: "Keyword suggestions failed",
        description:
          err instanceof Error ? err.message : "Could not suggest keywords.",
        variant: "destructive",
      });
    } finally {
      setDiscoveringKeywords(false);
    }
  }, [discoverKeywordSuggestions, toast]);

  const handleAcceptSuggestedKeywords = useCallback(
    async (suggestions?: string[]) => {
      const keywordsToAccept = suggestions ?? selectedSuggestions;
      if (keywordsToAccept.length === 0) return;

      setAcceptingKeywords(true);
      try {
        await api.keywords.createBatch(projectId, keywordsToAccept);
        await mutateSavedKeywords();

        if ((visibilitySchedules?.length ?? 0) === 0) {
          await api.visibility.schedules.create({
            projectId,
            query: keywordsToAccept[0],
            providers: [...DEFAULT_VISIBILITY_PROVIDERS],
            frequency: "weekly",
          });
          await mutateVisibilitySchedules();
        }

        toast({
          title: "Demand model updated",
          description: `${keywordsToAccept.length} keywords accepted and pushed into tracking.`,
        });
      } catch (err) {
        toast({
          title: "Failed to accept suggestions",
          description:
            err instanceof Error ? err.message : "Could not save keywords.",
          variant: "destructive",
        });
      } finally {
        setAcceptingKeywords(false);
      }
    },
    [
      mutateSavedKeywords,
      mutateVisibilitySchedules,
      projectId,
      selectedSuggestions,
      toast,
      visibilitySchedules,
    ],
  );

  const handleAcceptRecommendedCompetitors = useCallback(async () => {
    if (recommendedCompetitorDomains.length === 0) return;

    setAddingRecommendedCompetitors(true);
    try {
      await Promise.all(
        recommendedCompetitorDomains.slice(0, 3).map((domain) =>
          api.benchmarks.trigger({
            projectId,
            competitorDomain: domain,
          }),
        ),
      );
      toast({
        title: "Competitors mapped",
        description: "Recommended competitor benchmarks have been queued.",
      });
    } catch (err) {
      toast({
        title: "Failed to add recommended competitors",
        description:
          err instanceof Error ? err.message : "Could not queue benchmarks.",
        variant: "destructive",
      });
    } finally {
      setAddingRecommendedCompetitors(false);
    }
  }, [projectId, recommendedCompetitorDomains, toast]);

  const handleRunDemandFlow = useCallback(async () => {
    setRunningDemandFlow(true);
    try {
      const generated = await generatePersonas(DEMAND_FLOW_NICHE);
      await persistGeneratedPersonas(generated);

      let suggestionsToAccept = selectedSuggestions;
      if (keywordSuggestions.length === 0) {
        suggestionsToAccept = await discoverKeywordSuggestions();
      }

      if (suggestionsToAccept.length > 0) {
        await handleAcceptSuggestedKeywords(suggestionsToAccept);
      }
      if (recommendedCompetitorDomains.length > 0) {
        await handleAcceptRecommendedCompetitors();
      }

      toast({
        title: "Guided demand flow completed",
        description:
          "Personas, keywords, competitors, and schedules were advanced.",
      });
    } catch (err) {
      toast({
        title: "Guided setup failed",
        description:
          err instanceof Error
            ? err.message
            : "Could not complete guided demand setup.",
        variant: "destructive",
      });
    } finally {
      setRunningDemandFlow(false);
    }
  }, [
    discoverKeywordSuggestions,
    generatePersonas,
    handleAcceptRecommendedCompetitors,
    handleAcceptSuggestedKeywords,
    keywordSuggestions.length,
    persistGeneratedPersonas,
    recommendedCompetitorDomains.length,
    selectedSuggestions,
    toast,
  ]);

  const handleToggleSuggestion = useCallback((keyword: string) => {
    setSelectedSuggestions((prev) => toggleSelectedKeyword(prev, keyword));
  }, []);

  const handleAddCompetitor = useCallback(async () => {
    if (!newCompDomain) return;

    setAddingComp(true);
    try {
      await addCompetitor(newCompDomain);
      setNewCompDomain("");
    } catch (err) {
      toast({
        title: "Failed to add competitor",
        description:
          err instanceof Error ? err.message : "Please try again shortly.",
        variant: "destructive",
      });
    } finally {
      setAddingComp(false);
    }
  }, [addCompetitor, newCompDomain, toast]);

  const handleRemoveCompetitor = useCallback(
    async (id: string) => {
      try {
        await removeCompetitor(id);
      } catch (err) {
        toast({
          title: "Failed to remove competitor",
          description:
            err instanceof Error ? err.message : "Please try again shortly.",
          variant: "destructive",
        });
      }
    },
    [removeCompetitor, toast],
  );

  return {
    addingComp,
    newCompDomain,
    setNewCompDomain,
    keywordSuggestions,
    selectedSuggestions,
    discoveringKeywords,
    acceptingKeywords,
    addingRecommendedCompetitors,
    runningDemandFlow,
    handleGeneratePersonas,
    handleDiscoverKeywordSuggestions,
    handleAcceptSuggestedKeywords,
    handleAcceptRecommendedCompetitors,
    handleRunDemandFlow,
    handleToggleSuggestion,
    handleAddCompetitor,
    handleRemoveCompetitor,
  };
}
