"use client";

import { useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useApiSWR } from "@/lib/use-api-swr";
import { api, type BillingInfo } from "@/lib/api";
import { NarrativeSectionEditor } from "./narrative-section-editor";
import { Brain, Sparkles } from "lucide-react";
import type { NarrativeSection } from "@llm-boost/shared";

type NarrativeTone = "technical" | "business";

interface Props {
  crawlJobId: string;
}

export function NarrativeViewer({ crawlJobId }: Props) {
  const [tone, setTone] = useState<NarrativeTone>("technical");

  const { data: billing } = useApiSWR<BillingInfo>(
    "billing-info",
    useCallback(() => api.billing.getInfo(), []),
  );

  const plan = billing?.plan ?? "free";
  const isAgency = plan === "agency";
  const isPro = plan === "pro" || isAgency;

  const {
    data: narrative,
    isLoading,
    mutate,
  } = useApiSWR(
    isPro ? `narrative-${crawlJobId}-${tone}` : null,
    useCallback(() => api.narratives.get(crawlJobId, tone), [crawlJobId, tone]),
  );

  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = useCallback(async () => {
    setIsGenerating(true);
    try {
      await api.narratives.generate(crawlJobId, tone);
      mutate();
    } finally {
      setIsGenerating(false);
    }
  }, [crawlJobId, tone, mutate]);

  const handleSectionUpdate = useCallback(
    (updated: NarrativeSection) => {
      if (!narrative) return;
      const newSections = (narrative.sections as NarrativeSection[]).map((s) =>
        s.id === updated.id ? updated : s,
      );
      mutate({ ...narrative, sections: newSections }, false);
    },
    [narrative, mutate],
  );

  if (!isPro) {
    return (
      <div className="flex flex-col items-center justify-center space-y-4 rounded-lg border border-dashed p-12 text-center">
        <Brain className="h-10 w-10 text-muted-foreground" />
        <div>
          <p className="font-semibold">AI Analysis requires Pro or Agency</p>
          <p className="text-sm text-muted-foreground">
            Upgrade your plan to unlock AI-generated narrative reports
          </p>
        </div>
        <Button asChild>
          <a href="/dashboard/billing">Upgrade Plan</a>
        </Button>
      </div>
    );
  }

  const sections = (narrative?.sections as NarrativeSection[]) ?? [];

  return (
    <div className="space-y-6">
      {/* Header with tone toggle */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Button
            variant={tone === "technical" ? "default" : "outline"}
            size="sm"
            onClick={() => setTone("technical")}
          >
            Technical
          </Button>
          <Button
            variant={tone === "business" ? "default" : "outline"}
            size="sm"
            onClick={() => setTone("business")}
          >
            Business
          </Button>
        </div>
        {isAgency && (
          <p className="text-xs text-muted-foreground">
            Agency plan — click any section to edit
          </p>
        )}
      </div>

      {/* Content */}
      {isLoading ? (
        <div className="space-y-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-32 w-full" />
          ))}
        </div>
      ) : sections.length === 0 ? (
        <div className="space-y-4 py-12 text-center">
          <Sparkles className="mx-auto h-10 w-10 text-muted-foreground" />
          <p className="text-muted-foreground">
            No AI analysis generated yet for the{" "}
            <span className="font-medium">{tone}</span> tone.
          </p>
          <Button onClick={handleGenerate} disabled={isGenerating}>
            {isGenerating ? "Generating..." : "Generate AI Analysis"}
          </Button>
        </div>
      ) : (
        <div className="space-y-4">
          {sections.map((section) => (
            <NarrativeSectionEditor
              key={section.id}
              section={section}
              crawlJobId={crawlJobId}
              editable={isAgency}
              onSectionUpdate={handleSectionUpdate}
            />
          ))}
        </div>
      )}

      {/* Version info */}
      {narrative && (
        <p className="text-xs text-muted-foreground">
          Generated by {narrative.generatedBy} · v{narrative.version} ·{" "}
          {new Date(narrative.createdAt).toLocaleDateString()}
        </p>
      )}
    </div>
  );
}
